FROM php:8.2-cli

RUN apt-get update && apt-get install -y curl git unzip

COPY . /myapp
WORKDIR /myapp
RUN pwd

RUN ls

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer require --dev phpunit/phpunit ^9

RUN mkdir -p /myapp/etc/monnet
COPY config/config.defaults.php /myapp/etc/monnet/config.inc.php

COPY ci-docker/entry.sh /myapp/usr/local/bin/entry.sh
RUN chmod +x /myapp/usr/local/bin/entry.sh

RUN ./vendor/bin/phpunit --version

#CMD ["./vendor/bin/phpunit"]
CMD ["/usr/local/bin/entry.sh"]