FROM php:8.2-cli

RUN apt-get update && apt-get install -y curl git unzip
RUN docker-php-ext-install mysqli

COPY . /myapp
WORKDIR /myapp

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer require --dev phpunit/phpunit ^9

COPY config/config.defaults.php /etc/monnet/config.inc.php

COPY ci-docker/entry.sh /usr/local/bin/entry.sh
RUN chmod +x /usr/local/bin/entry.sh

RUN ./vendor/bin/phpunit --version

#CMD ["./vendor/bin/phpunit"]
CMD ["/usr/local/bin/entry.sh"]