FROM php:8.2-cli

RUN apt-get update && apt-get install -y curl git unzip

COPY . /myapp
RUN ls -la /myapp
WORKDIR /myapp

RUN ls -la

COPY ../config/config.defaults.php /etc/monnet/config.inc.php

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer require --dev phpunit/phpunit ^9

CMD ["./vendor/bin/phpunit"]
