FROM php:8.2-cli

RUN cat /etc/resolv.conf
RUN echo 1.1.1.1 > /etc/resolv.conf
RUN apt-get update && apt-get install -y curl git unzip

RUN echo "memory_limit = 512M" > $PHP_INI_DIR/php.ini

COPY . /myapp

WORKDIR /myapp

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN composer require --dev phpstan/phpstan
RUN composer require phpmailer/phpmailer
RUN composer require phpseclib/phpseclib

RUN ls -la /myapp
RUN ls -la /myapp/vendor/bin


ENV PATH="$PATH:/root/.composer/vendor/bin:/myapp/vendor/bin"

CMD ["phpstan", "analyse", "--configuration=/myapp/ci-docker/phpstan.neon", "."]
