services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: monnetadmin
      MYSQL_DATABASE: monnet
      MYSQL_USER: monnet
      MYSQL_PASSWORD: monnetadmin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  apache:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: apache_container
    restart: always
#    volumes:
#      - ./monnet:/var/www/html
    ports:
      - "8080:80"

volumes:
  mysql_data:
