name: CI for PHP App


#Ejecutar en Push/Branch/Main
on:
  push:
    branches:
      - main

#
jobs:
  build:
    runs-on: arc-runner-set

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y curl zstd git openssl zip

    - name: Setup PHP
      run: |
        sudo apt-get install -y php
        sudo apt-get install -y php-xml php-json php-mbstring php-tokenizer

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer
  
    - name: Install PHP dependencies
      run: |
        composer require --dev phpunit/phpunit

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --configuration phpunit.xml