version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/myapp
    command: ["./vendor/bin/phpunit"]
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: monnet
      MYSQL_USER: monnet
      MYSQL_PASSWORD: monnetadmin
      MYSQL_ROOT_PASSWORD: monnetadmin
    ports:
      - "3306:3306"

