<?php

/**
 *
 * @author diego/@/envigo.net
 * @copyright Copyright CC BY-NC-ND 4.0 @ 2020 - 2025 Diego Garcia (diego/@/envigo.net)
 */
!defined('IN_WEB') ? exit : true;

$cfg['monnet_version'] = 0.74;
$cfg['monnet_revision'] = 40;

$cfg['monnet_homepage'] = 'https://github.com/diegargon/monnet';
$cfg['agent_min_version'] = 0.184;
$cfg['agent_latest_version'] = 0.196;
$cfg['app_name'] = 'monnet';
$cfg['db_cfg_file'] = '/etc/monnet/config-db.json';

$cfg['allowed_images_ext'] = ['png', 'jpg', 'jpeg', 'gif', 'ico'];

/* TO DB */
$cfg['weather_widget'] = [
    'country' => 'vigo',
    'weather_api' => '89fe8d3a8486486fc682ba97dc28850f'
];

/* Hardware Manufacture */
$cfg['manufacture'] = [
    0 => ['id' => 0, 'name' => 'Unknown', 'img' => 'unknown.png'],

    /* Hardware / Fabricantes y Proveedores físicos */
    12 => ['id' => 12, 'name' => 'Samsung Electronics', 'img' => 'samsung.png'],
    13 => ['id' => 13, 'name' => 'Sony Corporation', 'img' => 'sony.png'],
    14 => ['id' => 14, 'name' => 'Dell Technologies', 'img' => 'dell.png'],
    15 => ['id' => 15, 'name' => 'Meta', 'img' => 'Meta.png'],
    16 => ['id' => 16, 'name' => 'IBM', 'img' => 'ibm.png'],
    17 => ['id' => 17, 'name' => 'Intel', 'img' => 'intel.png'],
    18 => ['id' => 18, 'name' => 'AMD', 'img' => 'amd.png'],
    19 => ['id' => 19, 'name' => 'Cisco Systems', 'img' => 'cisco_systems.png'],
    20 => ['id' => 20, 'name' => 'OPNSense', 'img' => 'opnsense.png'],
    21 => ['id' => 21, 'name' => 'Dlink', 'img' => 'dlink.png'],
    22 => ['id' => 22, 'name' => 'Tplink', 'img' => 'tplink.png'],
    23 => ['id' => 23, 'name' => 'Mikrotik', 'img' => 'mikrotik.png'],
    24 => ['id' => 24, 'name' => 'Supermicro', 'img' => 'supermicro.png'],
    25 => ['id' => 25, 'name' => 'Apple Inc.', 'img' => 'apple.png'],
    26 => ['id' => 26, 'name' => 'Western Digital', 'img' => 'wd.png'],
    27 => ['id' => 27, 'name' => 'Tenda', 'img' => 'tenda.png'],
    28 => ['id' => 28, 'name' => 'Fortinet', 'img' => 'fortinet.png'],
    29 => ['id' => 29, 'name' => 'Cisco Systems', 'img' => 'cisco_systems.png'],
    30 => ['id' => 30, 'name' => 'Huawei', 'img' => 'huawei.png'],
    31 => ['id' => 31, 'name' => 'Juniper Networks', 'img' => 'juniper.png'],
    32 => ['id' => 32, 'name' => 'NetGear', 'img' => 'netgear.png'],
    33 => ['id' => 33, 'name' => 'Asus', 'img' => 'asus.png'],
    34 => ['id' => 34, 'name' => 'Linksys', 'img' => 'linksys.png'],
    35 => ['id' => 35, 'name' => 'Zyxel', 'img' => 'zyxel.png'],
    36 => ['id' => 36, 'name' => 'Synology', 'img' => 'synology.png'],
    37 => ['id' => 37, 'name' => 'Ubiquiti Networks', 'img' => 'ubiquiti.png'],
    38 => ['id' => 38, 'name' => 'Palo Alto Networks', 'img' => 'paloalto.png'],
    39 => ['id' => 39, 'name' => 'Check Point Software Technologies', 'img' => 'checkpoint.png'],
    40 => ['id' => 40, 'name' => 'Aruba Networks', 'img' => 'aruba.png'],
    41 => ['id' => 41, 'name' => 'SonicWall', 'img' => 'sonicwall.png'],
    42 => ['id' => 42, 'name' => 'Truenas', 'img' => 'truenas.png'],
    43 => ['id' => 43, 'name' => 'Espressif Inc', 'img' => 'espressif.png'],
    44 => ['id' => 44, 'name' => 'Kyocera', 'img' => 'unknown.png'],
    45 => ['id' => 45, 'name' => 'Canon', 'img' => 'unknown.png'],
    46 => ['id' => 46, 'name' => 'Brother', 'img' => 'unknown.png'],
    47 => ['id' => 47, 'name' => 'Epson', 'img' => 'unknown.png'],
    48 => ['id' => 48, 'name' => 'Xerox', 'img' => 'unknown.png'],
    49 => ['id' => 49, 'name' => 'Lexmark', 'img' => 'unknown.png'],
    50 => ['id' => 50, 'name' => 'Ricoh', 'img' => 'unknown.png'],
    51 => ['id' => 51, 'name' => 'Konica Minolta', 'img' => 'unknown.png'],
    52 => ['id' => 52, 'name' => 'Microsemi', 'img' => 'unknown.png'],
    53 => ['id' => 53, 'name' => 'Marvell Technology Group', 'img' => 'unknown.png'],
    54 => ['id' => 54, 'name' => 'Broadcom', 'img' => 'broadcom.png'],
    55 => ['id' => 55, 'name' => 'IBM', 'img' => 'ibm.png'],
    56 => ['id' => 56, 'name' => 'Hewlett Packard', 'img' => 'hp.png'],
    57 => ['id' => 57, 'name' => 'Lenovo Data Center Group', 'img' => 'lenovo.png'],
    58 => ['id' => 58, 'name' => 'Fujitsu', 'img' => 'fujitsu.png'],
    59 => ['id' => 59, 'name' => 'NEC Corporation', 'img' => 'unknown.png'],
    60 => ['id' => 60, 'name' => 'Arista Networks', 'img' => 'arista.png'],
    61 => ['id' => 61, 'name' => 'F5 Networks', 'img' => 'unknown.png'],
    62 => ['id' => 62, 'name' => 'Lenovo', 'img' => 'lenovo.png'],
    63 => ['id' => 63, 'name' => 'NetApp', 'img' => 'netapp.png'],
    64 => ['id' => 64, 'name' => 'Seagate Technology', 'img' => 'seagate.png'],
    65 => ['id' => 65, 'name' => 'TPV Technology', 'img' => 'unknown.png'],

    /* Proveedores Cloud / Infraestructura */
    100 => ['id' => 100, 'name' => 'AWS', 'img' => 'aws.png'],
    101 => ['id' => 101, 'name' => 'Azure', 'img' => 'azure.png'],
    102 => ['id' => 102, 'name' => 'Google Cloud', 'img' => 'googlecloud.png'],
    103 => ['id' => 103, 'name' => 'ArubaCloud', 'img' => 'unknown.png'],
    104 => ['id' => 104, 'name' => 'IBM Cloud', 'img' => 'ibm.png'],
    105 => ['id' => 105, 'name' => 'Oracle Cloud', 'img' => 'oracle.png'],
    106 => ['id' => 106, 'name' => 'Alibaba Cloud', 'img' => 'alibaba.png'],
    107 => ['id' => 107, 'name' => 'Linode', 'img' => 'linode.png'],
    108 => ['id' => 108, 'name' => 'Scaleway', 'img' => 'scaleway.png'],
    109 => ['id' => 109, 'name' => 'Vultr', 'img' => 'unknown.png'],
    110 => ['id' => 110, 'name' => 'DigitalOcean', 'img' => 'digitalocean.png'],
    111 => ['id' => 111, 'name' => 'Hetzner', 'img' => 'hetzner.png'],
    112 => ['id' => 112, 'name' => 'OVH', 'img' => 'ovh.png'],
    113 => ['id' => 113, 'name' => 'Netcup', 'img' => 'unknown.png'],
    114 => ['id' => 114, 'name' => 'Cantabo', 'img' => 'unknown.png'],
    115 => ['id' => 115, 'name' => 'Altia', 'img' => 'unknown.png'],
    /* Networking (infraestructura con hardware) */
    500 => ['id' => 500, 'name' => 'Cloudflare', 'img' => 'cloudflare.png'],
    501 => ['id' => 501, 'name' => 'Akamai', 'img' => 'akamai.png'],
    502 => ['id' => 502, 'name' => 'Fastly', 'img' => 'fastly.png'],
    503 => ['id' => 503, 'name' => 'Amazon CloudFront', 'img' => 'aws.png'],
    504 => ['id' => 504, 'name' => 'Google Cloud CDN', 'img' => 'googlecloud.png'],
    505 => ['id' => 505, 'name' => 'Limelight Networks', 'img' => 'unknown.png'],
    506 => ['id' => 506, 'name' => 'EdgeCast', 'img' => 'unknown.png'],
];

/* Machine Type */
$cfg['machine_type'] = [
    0 => ['id' => 0, 'name' => 'Unknown', 'img' => 'unknown.png'],
    1 => ['id' => 1, 'name' => 'Physical/On-Premises', 'img' => 'unknown.png'],
    2 => ['id' => 2, 'name' => 'Virtual', 'img' => 'unknown.png'],
    4 => ['id' => 4, 'name' => 'Container', 'img' => 'unknown.png'],
    5 => ['id' => 5, 'name' => 'Cloud', 'img' => 'unknown.png'],
    6 => ['id' => 6, 'name' => 'Bare Metal Cloud', 'img' => 'unknown.png'],
];
/* OS */
$cfg['os'] = [
    0 => ['id' => 0, 'name' => 'Unknown', 'img' => 'unknown.png'],
    1 => ['id' => 1, 'name' => 'Generic Linux', 'img' => 'linux.png'],
    2 => ['id' => 2, 'name' => 'Windows 10', 'img' => 'windows10.png'],
    3 => ['id' => 3, 'name' => 'FreeBSD', 'img' => 'freebsd.png'],
    4 => ['id' => 4, 'name' => 'Android', 'img' => 'android.png'],
    5 => ['id' => 5, 'name' => 'iOS', 'img' => 'ios.png'],
    6 => ['id' => 6, 'name' => 'macOS', 'img' => 'macos.png'],
    7 => ['id' => 7, 'name' => 'Windows 7', 'img' => 'windows10.png'],
    8 => ['id' => 8, 'name' => 'Windows 8', 'img' => 'windows8.png'],
    9 => ['id' => 9, 'name' => 'Unix', 'img' => 'unix.png'],
    10 => ['id' => 10, 'name' => 'OpenBSD', 'img' => 'openbsd.png'],
    11 => ['id' => 11, 'name' => 'Solaris', 'img' => 'solaris.png'],
    12 => ['id' => 12, 'name' => 'AIX', 'img' => 'aix.png'],
    13 => ['id' => 13, 'name' => 'HP-UX', 'img' => 'hpux.png'],
    14 => ['id' => 14, 'name' => 'Chrome OS', 'img' => 'chromeos.png'],
    15 => ['id' => 15, 'name' => 'IBM i', 'img' => 'ibmi.png'],
    16 => ['id' => 16, 'name' => 'z/OS', 'img' => 'zos.png'],
    17 => ['id' => 17, 'name' => 'DOS', 'img' => 'dos.png'],
    18 => ['id' => 18, 'name' => 'RTOS', 'img' => 'rtos.png'],
    19 => ['id' => 19, 'name' => 'Plan 9 from Bell Labs', 'img' => 'plan9.png'],
    20 => ['id' => 20, 'name' => 'RouterOS', 'img' => 'mikrotik.png'],
    21 => ['id' => 21, 'name' => 'SwitchOS', 'img' => 'mikrotik.png'],
    22 => ['id' => 22, 'name' => 'FortiOS', 'img' => 'fortinet.png'],
    23 => ['id' => 23, 'name' => 'Truenas Core', 'img' => 'truenas.png'],
    24 => ['id' => 24, 'name' => 'Truenas Scale', 'img' => 'truenas.png'],
    25 => ['id' => 25, 'name' => 'Freenas', 'img' => 'freenas.png'],
    26 => ['id' => 26, 'name' => 'Windows 2019', 'img' => 'windows-server.png'],
    27 => ['id' => 27, 'name' => 'Windows 2016', 'img' => 'windows-server.png'],
    28 => ['id' => 28, 'name' => 'Windows 2022', 'img' => 'windows-server.png'],
    29 => ['id' => 29, 'name' => 'Windows 11', 'img' => 'windows-desktop.png'],
    30 => ['id' => 30, 'name' => 'DSM', 'img' => 'dsm.png'],
    31 => ['id' => 31, 'name' => 'ArubaOS', 'img' => 'unknown.png'],
    32 => ['id' => 32, 'name' => 'VMware', 'img' => 'vmware.png'],
    33 => ['id' => 33, 'name' => 'Other Proprietary', 'img' => 'proprietary.png'],
    34 => ['id' => 34, 'name' => 'Linux Embebbed', 'img' => 'embedded.png'],
    35 => ['id' => 35, 'name' => 'Tasmota', 'img' => 'embedded.png'],
    36 => ['id' => 36, 'name' => 'NetBSD', 'img' => 'netbsd.png'],
    37 => ['id' => 37, 'name' => 'Cisco IOS', 'img' => 'unknown.png'],
    38 => ['id' => 38, 'name' => 'Cisco NXOS', 'img' => 'unknown.png'],
    39 => ['id' => 39, 'name' => 'JunOS', 'img' => 'unknown.png'],
    40 => ['id' => 40, 'name' => 'PanOS', 'img' => 'unknown.png'],
    41 => ['id' => 41, 'name' => 'VyOS', 'img' => 'unknown.png'],
    42 => ['id' => 42, 'name' => 'AMI', 'img' => 'unknown.png'],
    43 => ['id' => 43, 'name' => 'OPNsense', 'img' => 'opnsense.png'],
    44 => ['id' => 44, 'name' => 'Proxmox VE', 'img' => 'proxmox.png'],
    45 => ['id' => 45, 'name' => 'QNX', 'img' => 'unknown.png'],
    46 => ['id' => 46, 'name' => 'Tizen', 'img' => 'unknown.png'],
    47 => ['id' => 47, 'name' => 'OpenVMS', 'img' => 'unknown.png'],
    48 => ['id' => 48, 'name' => 'Haiku', 'img' => 'unknown.png'],
    49 => ['id' => 49, 'name' => 'AmigaOS', 'img' => 'unknown.png'],
    50 => ['id' => 50, 'name' => 'BeOS', 'img' => 'unknown.png'],
    51 => ['id' => 51, 'name' => 'Debian', 'img' => 'unknown.jpg'],
    52 => ['id' => 52, 'name' => 'Ubuntu', 'img' => 'unknown.jpg'],
    53 => ['id' => 53, 'name' => 'Kali Linux', 'img' => 'unknown.jpg'],
    54 => ['id' => 54, 'name' => 'Arch Linux', 'img' => 'unknown.jpg'],
    55 => ['id' => 55, 'name' => 'IBM AIX', 'img' => 'unknown.jpg'],
    56 => ['id' => 56, 'name' => 'RHEL', 'img' => 'unknown.jpg'],
    57 => ['id' => 57, 'name' => 'CentOS', 'img' => 'unknown.jpg'],
    58 => ['id' => 58, 'name' => 'AlmaLinux', 'img' => 'unknown.jpg'],
    59 => ['id' => 59, 'name' => 'Rocky Linux', 'img' => 'unknown.jpg'],
    60 => ['id' => 60, 'name' => 'Fedora', 'img' => 'unknown.jpg'],
    61 => ['id' => 61, 'name' => 'OpenSUSE', 'img' => 'unknown.jpg'],
    62 => ['id' => 62, 'name' => 'SUSE Linux Enterprise', 'img' => 'unknown.jpg'],
    63 => ['id' => 63, 'name' => 'Slackware', 'img' => 'unknown.jpg'],
    64 => ['id' => 64, 'name' => 'Linux Mint', 'img' => 'unknown.jpg'],
    65 => ['id' => 65, 'name' => 'Elementary OS', 'img' => 'unknown.jpg'],
    66 => ['id' => 66, 'name' => 'Zorin OS', 'img' => 'unknown.jpg'],
    67 => ['id' => 67, 'name' => 'Garuda Linux', 'img' => 'unknown.jpg'],
    68 => ['id' => 68, 'name' => 'Pop!_OS', 'img' => 'unknown.jpg'],
    69 => ['id' => 69, 'name' => 'Clear Linux', 'img' => 'unknown.jpg'],
    70 => ['id' => 70, 'name' => 'EndeavourOS', 'img' => 'unknown.jpg'],
    71 => ['id' => 71, 'name' => 'Tails', 'img' => 'unknown.jpg'],
    72 => ['id' => 72, 'name' => 'Qubes OS', 'img' => 'unknown.jpg'],
    73 => ['id' => 73, 'name' => 'OpenWrt', 'img' => 'unknown.jpg'],
    74 => ['id' => 74, 'name' => 'pfSense', 'img' => 'unknown.jpg'],
    75 => ['id' => 75, 'name' => 'XCP-ng', 'img' => 'unknown.jpg'],
    76 => ['id' => 76, 'name' => 'XenServer', 'img' => 'unknown.jpg'],
    77 => ['id' => 77, 'name' => 'Citrix Hypervisor', 'img' => 'unknown.jpg'],
    78 => ['id' => 78, 'name' => 'Hyper-V', 'img' => 'unknown.jpg'],
    79 => ['id' => 79, 'name' => 'HarmonyOS', 'img' => 'unknown.jpg'],
    80 => ['id' => 80, 'name' => 'webOS', 'img' => 'unknown.jpg'],
    81 => ['id' => 81, 'name' => 'Fire OS', 'img' => 'unknown.jpg'],
    82 => ['id' => 82, 'name' => 'LineageOS', 'img' => 'unknown.jpg'],
    /* */
    200 => ['id' => 200, 'name' => 'KaiOS', 'img' => 'unknown.jpg'],
    201 => ['id' => 201, 'name' => 'Sailfish OS', 'img' => 'unknown.jpg'],
    202 => ['id' => 202, 'name' => 'PostmarketOS', 'img' => 'unknown.jpg'],
    203 => ['id' => 203, 'name' => 'Mobian', 'img' => 'unknown.jpg'],
    204 => ['id' => 204, 'name' => 'Whonix', 'img' => 'unknown.jpg'],
    205 => ['id' => 205, 'name' => 'RISC OS', 'img' => 'unknown.jpg'],
    206 => ['id' => 206, 'name' => 'Inferno', 'img' => 'unknown.jpg'],
    207 => ['id' => 207, 'name' => 'Minix', 'img' => 'unknown.jpg'],
    208 => ['id' => 208, 'name' => 'SerenityOS', 'img' => 'unknown.jpg'],
    209 => ['id' => 209, 'name' => 'SkyOS', 'img' => 'unknown.jpg'],
    210 => ['id' => 210, 'name' => 'HelenOS', 'img' => 'unknown.jpg'],
    211 => ['id' => 211, 'name' => 'MorphOS', 'img' => 'unknown.jpg'],
    212 => ['id' => 212, 'name' => 'Illumos', 'img' => 'unknown.jpg'],
    213 => ['id' => 213, 'name' => 'SmartOS', 'img' => 'unknown.jpg'],
    214 => ['id' => 214, 'name' => 'Contiki OS', 'img' => 'unknown.jpg'],
    215 => ['id' => 215, 'name' => 'RIOT OS', 'img' => 'unknown.jpg'],
    216 => ['id' => 216, 'name' => 'Zephyr OS', 'img' => 'unknown.jpg'],
    217 => ['id' => 217, 'name' => 'VxWorks', 'img' => 'unknown.jpg'],
    218 => ['id' => 218, 'name' => 'INTEGRITY OS', 'img' => 'unknown.jpg'],
    219 => ['id' => 219, 'name' => 'ThreadX', 'img' => 'unknown.jpg'],
    220 => ['id' => 220, 'name' => 'Fuchsia', 'img' => 'unknown.jpg'],
];

/* OS Family */
$cfg['os_family'] = [
    0 => ['id' => 0, 'name' => 'Unknown', 'img' => 'default.png'],
    1 => ['id' => 1, 'name' => 'Other', 'img' => 'default.png'],
    2 => ['id' => 2, 'name' => 'Linux', 'img' => 'default.png'],
    3 => ['id' => 3, 'name' => 'Windows', 'img' => 'default.png'],
    4 => ['id' => 4, 'name' => 'macOS', 'img' => 'default.png'],
    5 => ['id' => 5, 'name' => 'Android', 'img' => 'default.png'],
    6 => ['id' => 6, 'name' => 'iOS', 'img' => 'default.png'],
    7 => ['id' => 7, 'name' => 'BSD', 'img' => 'default.png'],
    8 => ['id' => 8, 'name' => 'Solaris', 'img' => 'default.png'],
    9 => ['id' => 9, 'name' => 'Unix', 'img' => 'default.png'],
    10 => ['id' => 10, 'name' => 'Chrome OS', 'img' => 'default.png'],
    11 => ['id' => 11, 'name' => 'AIX', 'img' => 'default.png'],
    12 => ['id' => 12, 'name' => 'HP-UX', 'img' => 'default.png'],
    13 => ['id' => 13, 'name' => 'FreeRTOS', 'img' => 'default.png'],
    14 => ['id' => 14, 'name' => 'QNX', 'img' => 'default.png'],
    15 => ['id' => 15, 'name' => 'Tizen', 'img' => 'default.png'],
    16 => ['id' => 16, 'name' => 'OpenVMS', 'img' => 'default.png'],
    17 => ['id' => 17, 'name' => 'AmigaOS', 'img' => 'default.png'],
    18 => ['id' => 18, 'name' => 'BeOS', 'img' => 'default.png'],
    19 => ['id' => 19, 'name' => 'Haiku', 'img' => 'default.png'],
];
/* System ROL */

$cfg['system_rol'] = [
    0 => ['id' => 0, 'name' => 'Unknown', 'img' => 'unknown.png'],
    1 => ['id' => 1, 'name' => 'Window Desktop', 'img' => 'windows-desktop.png'],
    2 => ['id' => 2, 'name' => 'Linux Desktop', 'img' => 'linux-desktop.png'],
    3 => ['id' => 3, 'name' => 'Iphone', 'img' => 'iphone.png'],
    4 => ['id' => 4, 'name' => 'Android Phone', 'img' => 'android-phone.png'],
    5 => ['id' => 5, 'name' => 'Apple Tablet', 'img' => 'ipad.png'],
    6 => ['id' => 6, 'name' => 'Android Tablet', 'img' => 'android-tablet.png'],
    7 => ['id' => 7, 'name' => 'TV', 'img' => 'tv.png'],
    8 => ['id' => 8, 'name' => 'Windows Server', 'img' => 'windows-server.png'],
    9 => ['id' => 9, 'name' => 'Linux Server', 'img' => 'linux-server.png'],
    10 => ['id' => 10, 'name' => 'Embedded', 'img' => 'embedded.png'],
    11 => ['id' => 11, 'name' => 'IOT', 'img' => 'iot.png'],
    12 => ['id' => 12, 'name' => 'Smart Home', 'img' => 'smart-home.png'],
    13 => ['id' => 13, 'name' => 'Wifi AP', 'img' => 'wifi-ap.png'],
    14 => ['id' => 14, 'name' => 'Security Camera', 'img' => 'cam2.png'],
    15 => ['id' => 15, 'name' => 'NVR', 'img' => 'nvr.png'],
    16 => ['id' => 16, 'name' => 'IPTV/TVBox', 'img' => 'tvbox.png'],
    17 => ['id' => 17, 'name' => 'Hypervisor', 'img' => 'hypervisor.png'],
    18 => ['id' => 18, 'name' => 'Router', 'img' => 'router.png'],
    19 => ['id' => 19, 'name' => 'Switch', 'img' => 'switch.png'],
    20 => ['id' => 20, 'name' => 'Mediacenter', 'img' => 'mediacenter.png'],
    21 => ['id' => 21, 'name' => 'NAS', 'img' => 'nas.png'],
    22 => ['id' => 22, 'name' => 'IOT Gateway', 'img' => 'iot-router.png'],
    23 => ['id' => 23, 'name' => 'P2P', 'img' => 'p2p.png'],
    24 => ['id' => 24, 'name' => 'Game Console', 'img' => 'gameconsole.png'],
    25 => ['id' => 25, 'name' => 'Printer', 'img' => 'printer.png'],
    26 => ['id' => 26, 'name' => 'Printer Server', 'img' => 'printer-server.png'],
    27 => ['id' => 27, 'name' => 'Log Server', 'img' => 'nas.png'],
    28 => ['id' => 28, 'name' => 'Database Server', 'img' => 'database-server.png'],
    29 => ['id' => 29, 'name' => 'VPN Server', 'img' => 'vpn-server.png'],
    30 => ['id' => 30, 'name' => 'Load Balancer', 'img' => 'load-balancer.png'],
    31 => ['id' => 31, 'name' => 'Container Orchestation', 'img' => 'container.png'],
    32 => ['id' => 32, 'name' => 'Version Control System', 'img' => 'vcs.png'],
    33 => ['id' => 33, 'name' => 'Mail Server/Gateway', 'img' => 'mail-server.png'],
    34 => ['id' => 34, 'name' => 'Web Server', 'img' => 'www.png'],
    35 => ['id' => 35, 'name' => 'File Server', 'img' => 'file-server.png'],
    36 => ['id' => 36, 'name' => 'Proxy', 'img' => 'balancer-balancer.png'],
    37 => ['id' => 37, 'name' => 'Management', 'img' => 'management.png'],
    38 => ['id' => 38, 'name' => 'Connectivity', 'img' => 'connectivity.png'],
];

$cfg['sys_availability'] = [
    0 => ['id' => 0, 'name' => 'None'],
    1 => ['id' => 1, 'name' => 'HA Active-Passive'],
    2 => ['id' => 1, 'name' => 'HA Active-Active'],
    3 => ['id' => 3, 'name' => 'Fault Tolerant'],
    4 => ['id' => 4, 'name' => 'Standalone/SPOF'],
    5 => ['id' => 5, 'name' => 'Clustered'],
    6 => ['id' => 6, 'name' => 'Cold Standby'],
    7 => ['id' => 7, 'name' => 'Warm Standby'],
    8 => ['id' => 8, 'name' => 'Geo-Redundant'],
    9 => ['id' => 9, 'name' => 'Disaster Recovery']
];

$cfg['check_method'] = [
    1 => 'ping',
    2 => 'port',
];

$cfg['cat_types'] = [
    1 => 'L_HOSTS',
    2 => 'L_LINKS',
    3 => 'L_SEARCH_ENGINE',
];

$cfg['access_link_types'] = [
    1 => 'www',
];

$cfg['task_trigger'] = [
    1 => ['name' => 'L_UNIQ', 'id' => 1],
    2 => ['name' => 'L_MANUAL', 'id' => 2],
    3 => ['name' => 'L_EVENT_RESPONSE', 'id' => 3],
    4 => ['name' => 'L_SCHEDULER', 'id' => 4],
    5 => ['name' => 'L_INTERVAL', 'id' => 5],
    6 => ['name' => 'L_OTHER_TASK', 'id' => 6],
];
