name: Deploy phpunit
#
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set-monnet
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker containers
        # Iniciar los servicios definidos en docker-compose
        run: docker-compose up -d --build    

      - name: Wait for MySQL to be ready
        # TODO check
        run: sleep 30            

      - name: Run PHPUnit tests
        run: |
          # Ejecutar las pruebas en el contenedor PHP
          docker-compose exec php ./vendor/bin/phpunit

      - name: Shutdown Docker containers
        run: |
          # Apagar y eliminar los contenedores
          docker-compose down
