name: Deploy phpunit
#
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set-monnet
    
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker BuildX version
        run: docker buildx version  

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Check Docker Compose version        
        run: docker-compose --version

      - name: Check current directory 1
        run: pwd

      - name: Build Docker images
        run: docker-compose -f ./ci-docker/docker-compose.yml build --no-cache

      - name: Check current directory 2
        run: pwd

      - name: Run Docker containers
        run: docker-compose -f ./ci-docker/docker-compose.yml up -d

      - name: Check current directory 3
        run: pwd

      - name: Check php container logs
        run: docker-compose -f ci-docker/docker-compose.yml logs php
        
      - name: Check containers
        run: docker-compose -f ci-docker/docker-compose.yml ps          

      - name: Shutdown Docker containers
        run: docker-compose -f ci-docker/docker-compose.yml down

      - name: Prune
        if: ${{ always() }}
        run: docker image prune -f
