name: Deploy phpunit
#
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set-monnet
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start MySQL service
        run: |
          docker run --name mysql-docker \
              -v $(pwd)/ci-docker/my.cnf:/etc/mysql/conf.d/my.cnf \
              --env='MYSQL_ROOT_PASSWORD=monnetadmin' \
              -d mysql:8
      - name: Build Docker image
        run: docker build -t my-app:latest -f ci-docker/Dockerfile-phpunit .

      - name: Wait for MySQL to start
        run: |
          for i in {1..30}; do
            if docker exec mysql-docker mysqladmin ping -uroot -pmonnetadmin --silent; then
              echo "MySQL is up and running!"
              break
            fi
            echo "Waiting for MySQL to start..."
            sleep 3
          done
      - name: Verify my.cnf in MySQL
        run: |
          docker exec mysql-docker cat /etc/mysql/conf.d/my.cnf
      - name: Configure MySQL root user permissions
        run: |
          docker exec -i mysql-docker mysql -uroot -pmonnetadmin -e "ALTER USER 'root'@'%' IDENTIFIED BY 'monnetadmin';"
          docker exec -i mysql-docker mysql -uroot -pmonnetadmin -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
          docker exec -i mysql-docker mysql -uroot -pmonnetadmin -e "FLUSH PRIVILEGES;"

      - name: Check containers
        run: docker ps -a

      - name: Check Mysql User
        run: docker exec -i mysql-docker mysql -uroot -pmonnetadmin -e "SELECT User, Host FROM mysql.user;"

      - name: Run Docker container
        run: docker run --rm my-app:latest   