name: Deploy phpunit
#
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set-monnet
    
    services:
      mysql-service:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: monnetadmin
          MYSQL_DATABASE: monnet
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y default-mysql-client

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Wait for MySQL to start
        run: |
          for i in {1..30}; do
            if mysql -h 127.0.0.1 -uroot -pmonnetadmin -e "SELECT 1;" >/dev/null 2>&1; then
              echo "MySQL is up and running!"
              break
            fi
            echo "Waiting for MySQL to start..."
            sleep 2
          done

      - name: Configure MySQL root user permissions
        run: |
          mysql -h mysql-service -uroot -pmonnetadmin -e "ALTER USER 'root'@'%' IDENTIFIED BY 'monnetadmin';"
          mysql -h mysql-service -uroot -pmonnetadmin -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
          mysql -h mysql-service -uroot -pmonnetadmin -e "FLUSH PRIVILEGES;"

      - name: Check containers
        if: ${{ always() }}
        run: docker ps -a

      - name: Run Docker container
        run: docker run --rm my-app:latest   