name: Deploy phpunit
#
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set-monnet
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-app:latest -f ci-docker/Dockerfile-phpunit .

      - name: Start MySQL service
        run: |
          docker run --name mysql --env 'MYSQL_ROOT_PASSWORD=monnetadmin' -e MYSQL_DATABASE=monnet -d mysql:8

      - name: Wait for MySQL to start
        run: |
          for i in {1..30}; do
            if docker exec mysql mysqladmin ping -uroot -pmonnetadmin --silent; then
              echo "MySQL is up and running!"
              break
            fi
            echo "Waiting for MySQL to start..."
            sleep 3
          done
      - name: Configure MySQL root user permissions
        run: |
          docker exec -i mysql mysql -uroot -pmonnetadmin -e "ALTER USER 'root'@'%' IDENTIFIED BY 'monnetadmin';"
          docker exec -i mysql mysql -uroot -pmonnetadmin -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
          docker exec -i mysql mysql -uroot -pmonnetadmin -e "FLUSH PRIVILEGES;"
      - name: Run Docker container
        run: docker run --rm my-app:latest   