name: Deploy phpunit
#
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set-monnet
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Docker BuildX version
        run: docker buildx version  

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verificar que se instaló correctamente

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Build docker-compose
        run: docker-compose -f docker/docker-compose.yml up --build -d

      - name: Wait for MySQL to be ready
        # TODO check
        run: sleep 30            

      - name: Run PHPUnit tests
        run: |
          # Ejecutar las pruebas en el contenedor PHP
          docker-compose exec php ./vendor/bin/phpunit

      - name: Shutdown Docker containers
        run: |
          # Apagar y eliminar los contenedores
          docker-compose down
