name: Deploy phpunit
#
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set-monnet
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check Docker BuildX version
        run: docker buildx version  

      - name: Build Docker image
        run: docker build -t my-app:latest -f ci-docker/Dockerfile-phpunit .

      - name: Run Docker container
        run: docker run --rm my-app:latest        