name: Deploy Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set-monnet
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PHP container
        uses: addnab/docker-run-action@v3
        with:
          image: php:latest
          options: -v ${{ github.workspace }}:/workspace
          run: php -r 'echo "Hello, World!";'
